'''
A coloured triangle is created from a row of colours, each of which is red, green or blue.
Successive rows, each containing one fewer colour than the last, are generated by considering the
two touching colours in the previous row. If these colours are identical, the same colour is used in
the new row. If they are different, the missing colour is used in the new row.
This is continued until the final row, with only a single colour, is generated.
'''

'''
Example:
R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
'''


def triangle(row):
    global rgb
    rgb = {'R', 'G', 'B'}
    global res
    while len(row) != 1:
        result = ''
        for i in range(len(row)-1):
            if row[i] == row[i+1]:
                result += row[i]
            else:
                temp = list(((rgb - set(row[i])) - set(row[i+1])))
                result += ''.join(str(i) for i in temp)
        #print(result, " result\n")
        #print(len(result), " len(result)\n")
        triangle(result)
        break
    if len(row) == 1:
        res = row
    return res

string = 'RRGBRGBB'
print(triangle(string))